modLoader = "javafml"
loaderVersion = "${loader_version_range}"
issueTrackerURL = "${issue_tracker}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
#updateJSONURL="http://myurl.me/"
#displayURL="http://example.com/"
logoFile = "logo.png"
# credits = "Thanks to the original author of Tome of Blood SadieLuna"
authors = "${mod_authors}"
description = '''${mod_description}'''

#[[mixins]]
#config="${mod_id}.mixins.json"

#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

# The coremods config file path is not configurable and is always loaded from META-INF/coremods.json

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId = "ars_nouveau"
type = "required"
versionRange="${ars_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId = "occultism"
type = "required"
versionRange="${occultism_version_range}"
ordering="NONE"
side="BOTH"